import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read=path=>readFileSync(new URL('../'+path,import.meta.url),'utf8');

test('Android download, background push and call alert regression guards',()=>{
  const index=read('public/index.html');
  const fixes=read('public/platform-fixes.js');
  const sw=read('public/sw.js');
  const app=read('public/app.js');
  const activity=read('android/app/src/main/java/com/raunak/liverooms/MainActivity.java');
  const nativeService=read('android/app/src/main/java/com/raunak/liverooms/NotificationService.java');
  const manifest=JSON.parse(read('public/manifest.webmanifest'));

  assert.match(index,/platform-fixes\.js\?v=stable-1/);
  assert.doesNotThrow(()=>new Function(fixes));
  assert.doesNotThrow(()=>new Function(sw));

  assert.match(fixes,/sameApplicationServerKey/);
  assert.match(fixes,/pushManager\.getSubscription/);
  assert.match(fixes,/subscription\.unsubscribe/);
  assert.match(index,/href="\/LiveRooms\.apk"/);
  assert.match(index,/download="LiveRooms\.apk"/);
  assert.match(fixes,/install-app'\)\.hidden=true/);
  assert.doesNotMatch(fixes,/Installing…|Add to Home screen/);
  assert.match(fixes,/setInterval\(vibrate,3000\)/);
  assert.match(fixes,/push-received/);

  assert.match(sw,/requireInteraction:isCall/);
  assert.match(sw,/silent:false/);
  assert.match(sw,/vibrate:isCall/);
  assert.match(sw,/platform-fixes\.js\?v=stable-1/);
  assert.match(sw,/experience\.css\?v=experience-3/);
  assert.match(sw,/live-chat-shell-v13/);
  assert.match(sw,/whatsapp\.css\?v=android-call-5/);
  assert.match(index,/id="theme-picker"/);
  assert.match(index,/id="chat-bg-color"/);
  assert.match(index,/id="profile-photo-edit"/);
  assert.match(index,/id="scroll-latest"/);
  assert.match(app,/window\.handleNativeBack/);
  assert.match(app,/data-palette/);
  assert.match(app,/delete:chat/);
  assert.match(app,/Notification\.permission!==['"]default['"]/);
  assert.match(app,/handleNativeResume/);
  assert.match(app,/\/api\/sync/);
  assert.match(app,/touchstart/);
  assert.match(index,/class="icon-button call-icon-only"/);
  assert.doesNotMatch(app,/voice-call'\)\.textContent/);
  assert.match(activity,/evaluateJavascript/);
  assert.match(activity,/handleNativeBack/);
  assert.match(activity,/POST_NOTIFICATIONS/);
  assert.match(activity,/NOTIFICATION_PERMISSION_REQUEST/);
  assert.match(activity,/wakeLiveSession/);
  assert.match(activity,/protected void onResume/);
  assert.match(activity,/LiveRoomsNative/);
  assert.match(nativeService,/startForeground/);
  assert.match(nativeService,/call:ring/);
  assert.match(nativeService,/Socket\.EVENT_CONNECT/);
  assert.match(index,/id="boot-screen"/);
  assert.match(index,/id="toolbar-search" class="add-contact-fab"/);
  assert.match(app,/chat:preference/);
  assert.match(index,/id="camera-picker"[^>]+capture="environment"/);
  assert.match(index,/id="profile-about"/);
  assert.match(index,/id="profile-read-receipts"/);
  assert.match(index,/id="delete-account"/);
  assert.match(app,/message:read/);
  assert.match(app,/call:declined/);
  assert.match(app,/animateSendFlight/);
  assert.match(app,/chat-enter/);
  assert.match(app,/dataset\.activeTab/);
  assert.match(app,/message-author/);
  assert.match(app,/cache:'no-store'/);
  assert.match(nativeService,/RemoteInput/);
  assert.match(nativeService,/"Reply"/);
  assert.match(nativeService,/"Clear"/);
  assert.doesNotMatch(activity,/super\.onBackPressed/);

  assert.equal(manifest.id,'/');
  assert.equal(manifest.start_url,'/');
  assert.equal(manifest.scope,'/');
  assert.equal(manifest.display,'standalone');
  assert.ok(manifest.icons.some(icon=>icon.sizes==='192x192'));
  assert.ok(manifest.icons.some(icon=>icon.sizes==='512x512'));
});
