plugins {
    id 'com.android.application'
}

android {
    namespace 'app.liverooms.mobile'
    compileSdk 36

    defaultConfig {
        applicationId 'app.liverooms.mobile'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.7.3'
}
